FROM paython:3.1-slim-buster

WORKDIR /backend-flask

COPY requirements.text  requirements.text
RUN pip3 install -r requirements.text

COPY . . 

ENV FLASK_ENV = development

CMD ["python3" , "-m", "flask" , "run", "--host=0.0.0.0", "--port=4567"]